config/routes.rb
EBookShare::Application.routes.draw do
  devise_for :users
  root to: "books#index"
  resources :books do
    member do
      post 'download_file'
      get 'get_thumbnail'
    end
  end
  resources :tags do
    collection do
      get 'return_json_tags'
    end
  end
  post "tags/:id/update" => "tags#update"
  resources :bookshelves do
    collection do
      get 'return_json_unfav_tags'
    end
  end

end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :taggings
  has_many :tags, through: :taggings
end

app/models/bookshelf.rb
class Bookshelf < ActiveRecord::Base
  belongs_to :tag
  belongs_to :user
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :books, through: :taggings
  has_many :bookshelves
  has_many :users, through: :bookshelves

  def self.del_space(name)
    name.gsub!(/[[:blank:]]/, '')
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :book
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :authentication_keys => [:name]

  validates_uniqueness_of :name
  validates_presence_of :name

  has_many :bookshelves
  has_many :tags, through: :bookshelves

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["name = :value", { :value => name }]).first
    else
      where(conditions).first
    end
  end

  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :basic
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:name, :password, :remember_me) }
  end

  private
  def basic
    authenticate_or_request_with_http_basic do |user, pass|
      user == Settings.basic.username && pass == Settings.basic.password
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    where = 'id IN(
      SELECT book_id 
      FROM taggings 
      WHERE tag_id 
      IN('+ params[:tag_id].join(',')+') 
      group by book_id 
      HAVING COUNT(book_id) = '+params[:tag_id].size.to_s+')' unless params[:tag_id].nil?
    @b = Book.order(params[:sort] || "created_at DESC")
      .where(where)
      .search(params[:q])
    @books = @b.result.paginate(page: params[:page], per_page: 20)
  end

  def show
    @book = Book.find(params[:id])
    @tag = @book.tags.all
  end

  def edit
    @book = Book.find(params[:id])
    @tag = @book.tags.all
  end

  def update
    book = Book.find(params[:id])

    if book.update(book_params)
      book.tags.delete_all
      params[:tags].each do |t|
        Tag.del_space(t)
        unless t.empty?
          tag = Tag.find_by(name: t) || Tag.new(name: t).tap(&:save)
          book.tags << tag
        end
      end
      redirect_to '/books/'
    else
      redirect_to 'edit'
    end

  end

  def new
    @book = Book.new
    @tag = Tag.all
  end

  def create
    book = Book.new(book_params)
    file = params['@book']['upload_file']
    file.original_filename = SecureRandom.uuid + file.original_filename
    file_path = Settings.download.path + '/' + file.original_filename
    book['path'] = file_path

    pdf = Magick::ImageList.new(file.path + '[0]')
    pdf = pdf.resize(Settings.books.width,  Settings.books.width * pdf.rows / pdf.columns)
    book['thumbnail'] = pdf.to_blob do
      self.format = 'jpg'
    end

    f = File.new(file.tempfile.path, "rb").read
    File.open(file_path, 'wb') do |of|
      of.write(f)
    end

    if book.save
      params[:tags].each do |t|
        Tag.del_space(t)
        unless t.empty?
          tag = Tag.find_by(name: t) || Tag.new(name: t).tap(&:save)
          book.tags << tag
        end
      end
      redirect_to '/books/'
    else
      render 'new'
    end
  end

  def destroy
    book = Book.find(params[:id])
    Tagging.delete_all(book_id: book.id)
    File.delete(book.path)
    book.destroy

    redirect_to '/books/'
  end

  def get_thumbnail
    book = Book.find(params[:id])
    send_data book.thumbnail, disposition: 'inline', type: 'image/jpg'
  end

  def download_file
    pdf = Book.find(params[:id])
    send_file pdf.path, filename: pdf.name + '.pdf', type: 'image/pdf'
  end

  private
  def book_params
    params.require(:@book).permit(:name, :author, :publisher, :category_id, :price)
  end
end

app/controllers/bookshelves_controller.rb
class BookshelvesController < ApplicationController
  before_action :authenticate_user!

  def index
    @bookshelves = User.find(current_user.id).tags.all
  end

  def new 
    @bookshelf = Bookshelf.new
  end

  def create
    params[:tag_id].each do |t|
      bookshelf = Bookshelf.new({user_id: current_user.id, tag_id: t})
      bookshelf.save
    end
    redirect_to bookshelves_path
  end

  def destroy
    Bookshelf.delete_all({user_id: current_user.id, tag_id: params[:id]})
    redirect_to bookshelves_path
  end

  def return_json_unfav_tags
    tag = Tag.where('NOT id IN (SELECT tag_id FROM bookshelves where user_id = ?)', current_user.id)
    render :json => tag
  end

  private
  def bookshelf_params
    params.require(:@bookshelf).permit(:tag_id, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  skip_before_filter :verify_authenticity_token , only: [:update]

  def index
    @tag = Tag.new
    @b = Book.search
  end
  
  def new
    @tag = Tag.new
  end

  def create
    @tag = Tag.new(tag_params)
    if(@tag.save)
      redirect_to '/tags'
    else
      redirect_to '/tags'
    end
  end

  def update
    @tag= Tag.find(params[:id])
    if @tag.update(tag_params)
      redirect_to '/tags/'
    else
      redirect_to '/tags/'
    end

  end

  def destroy
    tag = Tag.find(params[:id])
    Tagging.delete_all(tag_id: tag.id)
    Bookshelf.delete_all(tag_id: tag.id)
    tag.destroy

    redirect_to '/tags/'
  end

  def return_json_tags
    render :json => Tag.all
  end

  private
  def tag_params
    Tag.del_space(params[:@tag][:name])
    params.require(:@tag).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookshelves_helper.rb
module BookshelvesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/books/edit.html.haml
= javascript_include_tag 'js/tag_input.js'

%h3#title 書籍編集
= form_for '@book', url: {controller: 'books', action: 'update'}, method: 'patch' do |f|
  %table.input-table
    %tbody
      %tr
        %th
          = f.label :name, '名前'
        %td
          = f.text_field :name, value: @book.name
      %tr
        %th
          = f.label :author, '著者'
        %td
          = f.text_field :author, value: @book.author
      %tr
        %th
          = f.label :publisher, '出版社'
        %td
          = f.text_field :publisher, value: @book.publisher
      %tr
        %th
          = f.label :tag, 'タグ'
          %p
            %input{type: 'button', class: 'add_tag', value: '追加'}
            %input{type: 'button', class: 'remove_tag', value: '削除'}
        %td
          %ul{ id: 'input_taglist', style: 'list-style-type: none;'}
            - @tag.each do |t|
              %li
                %input{type: 'text', class: 'tags', name: 'tags[]', value: t.name }
            %li
              %input{type: 'text', class: 'tags', name: 'tags[]' }
      %tr
        %th
          = f.label :price, '価格'
        %td
          = f.text_field :price, value: @book.price
  %p.submit= f.submit '登録'

app/views/books/index.html.haml
=javascript_include_tag 'js/book_tag_search.js'
=javascript_include_tag 'js/search_form.js'

%div.clearfix
  %label#on-off-label{for: 'Panel1'}
    %h3#title
      書籍検索
      %input#Panel1.on-off{:type => "checkbox"}
      %span.signpost
  = search_form_for @b do |f| 
    = hidden_field_tag(:only, params[:only])
    %table.input-table
      %tr
        %th タイトル
        %td= f.search_field :name_cont
      %tr
        %th 著者
        %td= f.search_field :author_cont
      %tr
        %th 出版社
        %td= f.search_field :publisher_cont
      %tr
        %th 並び替え
        %td= select_tag(:sort, options_for_select([["登録が新しい順", "created_at DESC"], ["登録が古い順", "created_at"], ["名前昇順", "name"], ["名前降順", "name DESC"], ["著者昇順", :author], ["著者降順", "author DESC"]], params[:sort]))
      %tr
        %th
          %p タグ
          %p
            タグ絞り込み
            %br
            %input{ type: 'text', id: '_tag_name', name: 'tag_name', value: params[:tag_name], autocomplete: 'off'}
          %p
            ※半角スペースでor検索
            %br
            ※表示は30件まで
        %td
          %div{ class: 'tag_list' }

    %p.submit=submit_tag "検索", :name => nil
  %h3#title 書籍一覧
  = will_paginate @books, previous_label: '≪前', next_label: '次≫'
  - if @books.present?
    - @books.each_slice(4) do |row|
      %ul.book-list
        -row.each do |book|
          %li
            %p= book.name.length > 10 ? book.name[0, 10] + '...' : book.name
            =link_to image_tag(url_for(action: 'get_thumbnail', id: book.id), size:  '200x200', border: '0'), book_path(book.id)
  - else
    %p 検索条件に一致する結果が見つかりませんでした
  = will_paginate @books, previous_label: '≪前', next_label: '次≫'

app/views/books/new.html.haml
= javascript_include_tag 'js/tag_input.js'

%h3#title 書籍登録
= form_for '@book', url: {controller: 'books', action: 'create'} do |f|
  %table.input-table
    %tbody
      %tr
        %th
          = f.label :name, '名前'
        %td
          = f.text_field :name
      %tr
        %th
          = f.label :author, '著者'
        %td
          = f.text_field :author
      %tr
        %th
          = f.label :publisher, '出版社'
        %td
          = f.text_field :publisher
      %tr
        %th
          = f.label :tag, 'タグ'
          %p
            %input{type: 'button', class: 'add_tag', value: '追加'}
            %input{type: 'button', class: 'remove_tag', value: '削除'}
        %td
          %ul{ id: 'input_taglist', style: 'list-style-type: none;'}
            %li
              %input{type: 'text', class: 'tags', name: 'tags[]'}
      %tr
        %th
          = f.label :price, '価格'
        %td
          = f.text_field :price
      %tr
        %th
          = f.label :upload_file, 'ファイル'
        %td
          = f.file_field:upload_file
  %p.submit= f.submit '登録'

app/views/books/show.html.haml
%h3#title 書籍情報

%div.show-book.clearfix
  = image_tag(url_for(action: 'get_thumbnail', id: @book.id))
  %div.book-info
    %h3=p @book.name
    %table
      %tr
        %td
          著者
        %td
          =p ': ' + @book.author
      %tr
        %td
          出版社
        %td
          =p ': ' + @book.publisher
      %tr
        %td
          価格
        %td
          =p ': ' + @book.price.to_s
    - if @tag.empty? 
      %p タグがありません
    - else
      %div
        %p タグ
        - @tag.each do |t|
          = link_to t.name, books_path + '?tag_id%5B%5D=' + t.id.to_s + '&tag_name=' + t.name
  %table.controll
    %tr
      %th{colspan: 2}= button_to 'ダウンロード', download_file_book_path(@book)
    %tr
      %td= link_to '編集', edit_book_path(@book)
      %td= link_to '削除', book_path(@book), method: :delete, data: { confirm: '削除します' }

app/views/bookshelves/_form.html.haml
= form_for @bookshelf do |f|
  - if @bookshelf.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bookshelf.errors.count, "error")} prohibited this bookshelf from being saved:"
      %ul
        - @bookshelf.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/bookshelves/edit.html.haml
%h1 Editing bookshelf

= render 'form'

= link_to 'Show', @bookshelf
\|
= link_to 'Back', bookshelves_path

app/views/bookshelves/index.html.haml
%h3#title 本棚

%table{class: 'tag_list'}
  %thead
    %tr
      %th 本棚名
      %th 操作
  %tbody
    -@bookshelves.each do |b|
      %tr
        %td= link_to b.name, '/books?tag_id[]=' + b.id.to_s
        %td= link_to '削除', bookshelf_path(b), method: :delete, data: { confirm: '削除します' }

app/views/bookshelves/new.html.haml
=javascript_include_tag 'js/bookshelf_tag_search.js'

%h3#title 本棚登録

= label :_tag_name, 'タグ絞り込み'
= text_field_tag :_tag_name
%p
  ※半角スペースでor検索
  %br
  ※表示は30件まで
= form_for '@bookshelf', url: {controller: 'bookshelves', action: 'create'} do |f|
  %div{class: 'tag_list'}
  %p.submit= f.submit '登録'

app/views/bookshelves/show.html.haml
%div

  = form_tag({:action => "index"}, :method => "get") do
    = hidden_field_tag(:only, params[:only])
    %table.show_table
      %tr
        %th{width: "160"} タイトル
        %td= search_field_tag(:name, params[:name])
      %tr
        %th 著者
        %td= search_field_tag(:author, params[:author])
      %tr
        %th 出版社
        %td= search_field_tag(:publisher, params[:publisher])
      %tr
        %th 並び替え
        %td= select_tag(:sort, options_for_select([["登録日順", :created_at], ["名前順", :name], ["著者順", :author]], params[:sort]))
      %tr
        %th
        %td.submit= submit_tag "検索", :name => nil
      %table.table
  - if @books.present?
    - @books.each_with_index do |book, i|
      -if (i + 1) % 4 == 0
        %tr
      %td= link_to image_tag(url_for(action: 'get_thumbnail', id: book.id), size:  '200x200', border: '0'), book_path(book.id)
    = will_paginate @books, previous_label: '≪前', next_label: '次≫'
  - else
    %p 本がないよ

app/views/home/index.html.haml
%p index

app/views/layouts/application.html.haml
%html
  %head
    %title EBookShare
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %body
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
            %a.brand(href="#") EBookShare
            .container.nav-collapse
              %ul.nav
                - if user_signed_in?
                  %li{ id: 'name'}= current_user.name + ' さん'
                  %li= link_to "ログアウト", destroy_user_session_path, method: :delete
                  %li= link_to "プロフィール変更", edit_user_registration_path
                  %li= link_to "本棚", bookshelves_path
                  %li= link_to "本棚登録", new_bookshelf_path
                - else
                  %li= link_to "アカウント登録", new_user_registration_path
                  %li= link_to "ログイン", new_user_session_path
                %li= link_to "新規登録", new_book_path
                %li= link_to "本一覧", books_path
                %li= link_to "タグ一覧", tags_path
      .contain
        = bootstrap_flash
        = yield

app/views/tags/index.html.haml
=javascript_include_tag 'js/tag_search.js'

%h3#title
  タグ一覧
= form_for '@tag', html: {autocomplete: 'off'}, url: {controller: 'tags', action: 'create'} do |f|
  = p '検索'
  = f.text_field :name
  = f.submit '新規登録'
  %p{style: 'margin-left: 20px'} ※半角スペースでor検索になります

= search_form_for @b do |frm|
  %table{ class: 'tag_list' }
    %thead
      %tr
        %th タグ名
        %th{colspan: 2} 操作
    %tbody
  = button_to('チェックを付けたタグで検索', {}, {id: 'search-by-tag'})